### ISSUE TITLE
刚也想做个stcduino

### ISSUE THREAD

**Issue by tap6** [bootdisk/STCduino#1]
然后呢哥们，咱就是说有个项目了，但是五年了你还没上传代码吗。。。

**Comment by bootdisk** [comment]
兄弟你能笑死我。这是刚入门的时候的想法，不太成熟，坑填不上了。不过现在有人做出类似产品了，天问51，你可以试试

**Comment by tap6** [comment]
卧槽我看了一下，这玩意儿做的好牛逼啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bootdisk/STCduino"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 晚上9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bootdisk/STCduino] 刚也想做个stcduino (Issue #1)





 
兄弟你能笑死我。这是刚入门的时候的想法，不太成熟，坑填不上了。不过现在有人做出类似产品了，天问51，你可以试试
